// all products types
export const GET_PRODUCTS_START = "GET_PRODUCTS_STAR";
export const GET_PRODUCTS_SUCCESS = "GET_PRODUCTS_SUCCESS";
export const GET_PRODUCTS_FAILD = "GET_PRODUCTS_FAILD";
export const GET_PRODUCTS_END = "GET_PRODUCTS_END";

// top products types
export const GET_TOP_PRODUCTS_START = "GET_TOP_PRODUCT_STAR";
export const GET_TOP_PRODUCTS_SUCCESS = "GET_TOP_PRODUCT_SUCCESS";
export const GET_TOP_PRODUCTS_FAILD = "GET_TOP_PRODUCT_FAILD";
export const GET_TOP_PRODUCTS_END = "GET_TOP_PRODUCT_END";

// all category types
export const GET_ALL_CATEGORY_START = "GET_ALL_CATEGORY_STAR";
export const GET_ALL_CATEGORY_SUCCESS = "GET_ALL_CATEGORY_SUCCESS";
export const GET_ALL_CATEGORY_FAILD = "GET_ALL_CATEGORY_FAILD";
export const GET_ALL_CATEGORY_END = "GET_ALL_CATEGORY_END";

// one product
export const GET_PRODUCT_START = "GET_PRODUCT_STAR";
export const GET_PRODUCT_SUCCESS = "GET_PRODUCT_SUCCESS";
export const GET_PRODUCT_FAILD = "GET_PRODUCT_FAILD";
export const GET_PRODUCT_END = "GET_PRODUCT_END";

// one category types
export const GET_CATEGORY_START = "GET_CATEGORY_STAR";
export const GET_CATEGORY_SUCCESS = "GET_CATEGORY_SUCCESS";
export const GET_CATEGORY_FAILD = "GET_CATEGORY_FAILD";
export const GET_CATEGORY_END = "GET_CATEGORY_END";
